name: Run B3 Report Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18 * * 1-5'  # Executa dias úteis às 18:00 (6PM UTC = 15h BR)

jobs:
  run-b3-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup R Environment
        uses: r-lib/actions/setup-r@v2

      - name: Install Required R Packages
        run: |
          Rscript -e "install.packages(c('yfR', 'dplyr', 'TTR', 'purrr', 'tidyr', 'readr'), repos='https://cloud.r-project.org')"

      - name: Yahoo Package
        run: |
          Rscript -e "install.packages('remotes'); remotes::install_github('msperlin/yfR')"

      - name: Run B3 Report Script
        run: Rscript B3_Report.R

      - name: Upload CSV Report Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: csv-report
          path: Relatorios/*.csv
