name: Run CheckB3Stock Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18 * * 1-5'  # Executa dias úteis às 18:00 (6PM UTC = 15h BR)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup R Environment
        uses: r-lib/actions/setup-r@v2

      - name: Install Required R Packages
        run: |
          Rscript -e "install.packages(c('yfR', 'ggplot2', 'dplyr', 'TTR', 'gridExtra', 'scales', 'tidyquant'), repos='https://cloud.r-project.org')"

      - name: Run CheckB3Stock Script
        run: Rscript CheckB3Stock.R

      # Caso seu script gere um CSV e/ou imagem, certifique-se de que os arquivos são gerados
      # com os nomes correspondentes abaixo; caso contrário, remova ou ajuste as etapas de upload.
      - name: Upload CSV Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: csv-output
          path: resultado.csv

      - name: Upload Plot Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: plot-output
          path: grafico.png
