name: Daily Stock Analysis

on:
  schedule:
    - cron: '0 18 * * 1-5'  # Executa dias úteis às 18:00 (6PM UTC = 15h BR)
  workflow_dispatch:  # Permite execução manual

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install yfinance tabulate

    - name: Run analysis
      env:
        TICKERS: ${{ secrets.TICKERS }}
        SERVICEMAIL: ${{ secrets.SERVICEMAIL }}
        DESTINATARIOS: ${{ secrets.DESTINATARIOS }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        APP_NAME: ${{ secrets.APP_NAME }}
        OUTPUT_PATH: './reports'
      run: |
        mkdir -p reports
        python B3_Rec_Sel_List_Top.py

    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: stock-report
        path: ./reports/*.csv
