name: Daily Stock Analysis

on:
  schedule:
    - cron: '0 18 * * 1-5'  # Executa dias úteis às 18:00 (6PM UTC = 15h BR)
  workflow_dispatch:  # Permite execução manual

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install yfinance tabulate

    - name: Run analysis
      env:
        TICKERS: ${{ secrets.TICKERS }}          # Exemplo: "PETR4\nVALE3\nBBDC4"
        DESTINATARIOS: ${{ secrets.DESTINATARIOS }} # Exemplo: "Nome,email\nOutro,outro@email.com"
        SERVICEMAIL: ${{ secrets.SERVICEMAIL }}  # Seu e-mail completo
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }} # Senha de app do Gmail
        APP_NAME: ${{ secrets.APP_NAME }}         # Nome do remetente
        OUTPUT_PATH: './reports'
      run: |
        mkdir -p reports
        python B3_Rec_Sel_List_Top.py
      continue-on-error: true

    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: stock-report
        path: ./reports/*.csv
    
    - name: Check if report exists
      run: |
        if [ ! -f ".reports/*.csv" ]; then
          echo "Nenhum relatório foi gerado."
          exit 1
        fi 
    
    - name: Save logs
      uses: actions/upload-artifact@v3
      with:
        name: analysis-logs
        path: .logs/*.log
